// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	NEXT_CACHE_WORKERS_KV: KVNamespace;
	NEXTJS_ENV: string;
	DATABASE: D1Database;
	NEXT_CACHE_REVALIDATION_WORKER: Fetcher;
	ASSETS: Fetcher;
}
